service: gas-data

provider:
  name: aws
  runtime: python3.6
  role: arn:aws:iam::451093560309:role/service-role/gasDataRole
  region: eu-west-2

package:
  individually: true

functions:
  NG-get-file:
    handler: get_NG_data.lambda_handler
    events:
      - schedule: rate(6 minutes)
    environment:
      NG_Terminal_URL: http://mip-prod-web.azurewebsites.net/InstantaneousViewFileDownload/DownloadFile
      SNS_Topic_ARN: arn:aws:sns:eu-west-2:451093560309:NG_terminals
    package:
      include:
        - Lambda-NG-get-file
      artifact: _build/gas-data-dev-NG-get-file.zip

  GTS-get-file:
    handler: get_GTS_data.lambda_handler
    timeout: 30
    events:
      - schedule: cron(5 0/1 * * ? *)
    environment:
      SNS_Topic_ARN: arn:aws:sns:eu-west-2:451093560309:GTS_Terminals
      SNS_Error_ARN: arn:aws:sns:eu-west-2:451093560309:NG_test
    package:
      include:
        - Lambda-GTS-get-file
      artifact: _build/gas-data-dev-GTS-get-file.zip

  NG-process-data:
    handler: process_NG_data.lambda_handler
    events:
      - sns: arn:aws:sns:eu-west-2:451093560309:NG_terminals
    environment:
      RDS_Instance_Endpoint: gasdb.csomj93pkcws.eu-west-2.rds.amazonaws.com
      SNS_Error_ARN: arn:aws:sns:eu-west-2:451093560309:NG_test
    package:
      include:
        - Lambda-NG-process-data
        - DB_Tools
      artifact: _build/gas-data-dev-NG-process-data.zip

  NG-query-data:
    handler: query_NG_data.lambda_handler
    environment:
      RDS_Instance_Endpoint: gasdb.csomj93pkcws.eu-west-2.rds.amazonaws.com
    package:
      include:
        - Lambda-NG-API-Query
        - DB_Tools
      artifact: _build/gas-data-dev-NG-query-data.zip


plugins:
  - serverless-package-python-functions

custom:
  pkgPyFuncs: # plugin configuration
    buildDir: _build
    requirementsFile: 'requirements.txt'
    cleanup: true